config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'homes#top'
  get 'about' => 'homes#about'
  resources :books, only: [:index, :create, :show, :edit, :update, :destroy]
  resources :users, only: [:index, :show, :edit, :update]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user, optional: true

  validates :title, presence: true
  validates :body, presence: true, length: { maximum:200 }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  attachment :image

  validates :name, presence: true, uniqueness: true,
                   length: { minimum: 3, maximum: 20 }
  validates :profile, length: { maximum: 50 }



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 before_action :authenticate_user!,except: [:top, :about]
 before_action :configure_permitted_parameters, if: :devise_controller?
   def after_sign_in_path_for(resource)
    user_path(current_user.id)
   end
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :password, :password_confirmation, :remember_me])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :baria_book, only: [:edit, :update]

  def index
    @user = current_user
    @book = Book.new
    @books = Book.page(params[:page]).reverse_order
  end

  def create
    @user = current_user
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      @books = Book.page(params[:page]).reverse_order
      @user = current_user
      render :index
    end
  end

  def show
    @book = Book.new
    @show_book = Book.find(params[:id])
    @user = @show_book.user
    @books = @user.books.page(params[:page]).reverse_order


  end

  def edit
    @book = Book.find(params[:id])

  end

  def update
    @book = Book.find(params[:id])
    @book.user_id = current_user.id
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book)
    else
      render action: :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.user_id = current_user.id
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def baria_book
    unless Book.find(params[:id]).user_id == current_user.id
      redirect_to books_path
    end
  end



end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :baria_user, only: [:edit, :update]

  def index
    @user = current_user
    @users = User.page(params[:page]).reverse_order
    @book = Book.new
  end

  def show
    @book = Book.new
    @user = User.find(params[:id])
    @books = @user.books.page(params[:page]).reverse_order
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully"
      redirect_to user_path(@user.id)
    else
      render action: :edit
    end

  end

  private

  def user_params
    params.require(:user).permit(:name, :profile, :image)
  end

  def baria_user
    unless User.find(params[:id]).id == current_user.id
        redirect_to user_path(current_user)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_books.html.erb
  <div class="col-md-8 offset-md-1">
    <h2 class="books-heading">Books</h2>
    <table class="table table-hover table-inverse">
      <thead>
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% books.each do |book| %>
        <tr>
          <td><%= attachment_image_tag book.user, :image, size: "40x40", format: 'jpeg', fallback: "no_image.jpg" %></td>
          <td><%=link_to book_path(book), method: :get do %><%= book.title %><% end %></td>
          <td><%= book.body %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>

app/views/books/_leftside.html.erb
<div class="col-md-3">
  <h2 class="User-heading mb-1">User info</h2>
  <%= attachment_image_tag user, :image, size: "100x100", format: 'jpeg', fallback: "no_image.jpg" %>
  <table class="table">
    <tbody>
      <tr></tr>
      <tr>
        <th>name</th>
        <th><%= user.name %></th>
        </tr>
      <tr>
        <th>introduction</th>
        <th><%= user.profile %></th>
      </tr>
    </tbody>
  </table>
  <div class="row">
    <%= link_to edit_user_path(user), class:"btn btn-outline-secondary btn-block fas fa-user-cog mt-3", method: :get do %><% end %>
  </div>

  <h2 class="new-heading mt-3">New book</h2>
  <%= form_with model:book, local:true do |f| %>
  <div class="new-contents form-group">
    <label for="book_title">Title</label><br>
    <div><%= f.text_field :title, class: "new-text form-control" %></div>
  </div>
  <div class="new-contents form-group">
    <label for="book_body">Opinion</label><br>
    <div><%= f.text_area :body,class: "new-text form-control" %></div>
  </div>
  <div class="form-group">
    <%= f.submit 'Create Book', class: "btn btn-success" %>
  </div>
  <% end %>
</div>

app/views/books/edit.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved:
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>
<div class="container">
  <div class="raw">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1 class="edit-heading">Editing Book</h1>
      <%= form_with model:@book, local:true do |f| %>
        <div class="edit-contents form-group">
          <p>Title</p>
          <div><%= f.text_field :title, class: "edit-text form-control" %></div>
        </div>
        <div class="edit-contents form-group">
          <p>Opinion</p>
          <div><%= f.text_area :body,class: "edit-text form-control" %></div>
        </div>
        <div class="form-group">
          <%= f.submit 'Update Book', class: "btn btn-success" %>
        </div>
      <% end %>
      <div class="show-back">
        <%= link_to "Show", book_path(@book) %>
        <!--EditとBackの間の棒-->|
        <%= link_to "Back", books_path %>
      </div>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved:
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <%= render 'books/leftside', book: @book, user: @user %>

      <%= render 'books/books', books: @books, user: @user %>
    </div>
  </div>
<%= paginate @books %>

app/views/books/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <%= render 'books/leftside', book: @book, user: @user %>

    <div class="col-md-8 offset-md-1">
      <h2 class="detail-heading">Book detail</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= attachment_image_tag @show_book.user, :image, size: "40x40", format: 'jpeg', fallback: "no_image.jpg" %></td>
            <td><%=link_to book_path(@show_book), method: :get do %><%= @show_book.title %><% end %></td>
            <td><%= @show_book.body %></td>
            <% if @user.id == current_user.id %>
            <td><%= link_to "Edit", edit_book_path(@show_book), class:"btn btn-success btn-sm" %></td>
            <td><%= link_to "Destroy", book_path(@show_book), class:"btn btn-danger btn-sm", method: :delete, data: {confirm: "本当に消しますか？"} %></td>
            <% end %>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>
<%= paginate @books %>

app/views/homes/about.html.erb
<div class="container">
	<div class="row">
		<div class="mx-auto px-3">
			<h1 class="about-heading">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
		</div>
	</div>
</div>

app/views/homes/top.html.erb
<div class="container">
	<div class="row">
			<div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
					<h1 class="top-heading">welcome to <i class="fas fa-book"></i><strong>Bookers</strong> !!</h1>
					<p class="top-contents">In <i class="fas fa-book"></i><strong>Bookers</strong>,</p>
					<p class="top-contents">you can share and exchange your opinions , inpressions , and emotions</p>
					<p class="top-contents">about various books!</p>
					<div class="btn-wrapper col-10 mx-auto">
							<div class="row">
									<%= link_to "Log in", new_user_session_path, class:"btn btn-info btn-sm btn-block mb-3 sign_in" %>
							</div>
							<div class="row">
									<%= link_to "Sign Up", new_user_registration_path, class:"btn btn-success btn-sm btn-block sign_up" %>
							</div>
					</div>
			</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
	  <header>
			<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3">
				<div class="container">
					<%= link_to "Bookers", root_path, class: 'navbar-brand' %>
					<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expand="false" aria-label="Toggle navigation">
						<span class="navbar-toggler-icon"></span>
					</button>
					<div class="collapse navbar-collapse" id="navbarNavDropdown">
						<ul class="navbar-nav ml-auto">
							<% if user_signed_in? %>
							<li>
								<%= link_to user_path(current_user.id), class: 'fas fa-home nav-link text-light', method: :get do %> Home<% end %>
							</li>
							<li>
								<%= link_to users_path, class: 'fas fa-users nav-link text-light', method: :get do %> Users<% end %>
							</li>
							<li>
								<%= link_to books_path, class: 'fas fa-book-open nav-link text-light', method: :get do %> Books<% end %>
							</li>
							<li>
								<%= link_to destroy_user_session_path, class: 'fas fa-sign-out-alt nav-link text-light', method: :delete do %> logout<% end %>
							</li>
							<% else %>
							<li>
								<%= link_to root_path, class: 'nav-link text-light fas fa-home', method: :get do %> Home<% end %>
							</li>
							<li>
								<%= link_to about_path, class: 'nav-link text-light fas fa-link', method: :get do %> About<% end %>
							</li>
							<li>
								<%= link_to new_user_registration_path, class: 'nav-link text-light fas fa-user-plus', method: :get do %> sign up<% end %>
							</li>
							<li>
								<%= link_to new_user_session_path, class: 'nav-link text-light fas fa-sign-in-alt', method: :get do %> login<% end %>
							</li>
							<% end %>
						</ul>
					</div>
				</div>
			</nav>
	  </header>

	  <main>
	    <% if flash[:notice] %>
       	<div class="notice"><%= flash[:notice] %></div>
      <% end %>
			<%= yield %>
	  </main>

	  <footer>
		  <div class="container mt-5">
			  <div class="row">
				  <div class="mx-auto">
					  <p>CopyRight Infratop.inc</p>
				  </div>
			  </div>
		  </div>
	  </footer>

  </body>
</html>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <%= @user.errors.count %>errors prohibited this obj from being saved:
  <% @user.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px px-sm-0 mx-auto">
      <h2>User info</h2>
      <%= form_with model:@user, local:true do |f| %>
        <div class="edit-contents form-group">
          <label for="user_name">Name</label>
          <div><%= f.text_field :name, class: "edit-user-text form-control" %></div>
        </div>
        <div class="edit-contents form-group">
          <label for="inputImage">Image</label><br>
          <%= f.attachment_field :image, placeholder: "プロフィール画像" %>
        </div>
        <div class="edit-contents form-group">
          <label for="user_profile">introduction</label>
          <div><%= f.text_area :profile, class: "edit-user-text form-control" %></div>
        </div>
        <div class="form-group">
          <%= f.submit 'Update User', class: "btn btn-secondary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <%= render 'books/leftside', book: @book, user: @user %>

    <div class="col-md-8 offset-md-1">
      <h2 class="Users-heading">Users</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
          <tr>
            <td>
              <%= link_to user_path(user), method: :get do %>
                <%= attachment_image_tag user, :image, size: "40x40", format: 'jpeg', fallback: "no_image.jpg" %>
              <% end %>
              </td>
            <td><%= user.name %></td>
            <td><%= link_to "Show", user_path(user) %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
  <div class="container px-5 px-sm-0">
    <div class="row">
      <%= render 'books/leftside', book: @book, user: @user %>

      <%= render 'books/books', books: @books, user: @user %>      
    </div>
  </div>
<%= paginate @books %>